### ISSUE TITLE
关于Decision Generator部分模型的问题？

### ISSUE THREAD

**Issue by Ethereal-sakura** [ggg0919/cantor#2]
作者你好，感谢你提供了如此棒的实验。在阅读论文和代码的时候我有一个问题，在Decision Generator部分，代码中是传入了image的，但是gpt3.5是无法输入image的，所以想问一下论文中的Cantor(GPT-3.5)是怎么做的呢？

**Comment by ggg0919** [comment]
> 作者你好，感谢你提供了如此棒的实验。在阅读论文和代码的时候我有一个问题，在Decision Generator部分，代码中是传入了image的，但是gpt3.5是无法输入image的，所以想问一下论文中的Cantor(GPT-3.5)是怎么做的呢？

你好，GPT-3.5是使用图片的caption。

**Comment by Ethereal-sakura** [comment]
明白，感谢回答！
